In [ ]:
import numpy as np

# Basics

In [ ]:
mylist = [1,2,3]

create an array with numpy

In [ ]:
np.array(mylist)

array([1, 2, 3])

In [ ]:
nested_list = [[1,2], [3,4], [5,6]]

numpy will create a matrix from a nested list

In [ ]:
np.array(nested_list)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [ ]:
# create a matrix with zeros
np.zeros(3) # converting to floating zero numbers

array([0., 0., 0.])

create a 4x4 matrix

In [ ]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.zeros((4,10)) # 4 rows, 10 columns

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.ones(3) # the same but with ones

array([1., 1., 1.])

In [ ]:
np.linspace(0,10,3) # 3 numbers between 0 and 10

array([ 0.,  5., 10.])

In [ ]:
np.linspace(0,10,22) # 22 numbers between 0 and 10

array([ 0.        ,  0.47619048,  0.95238095,  1.42857143,  1.9047619 ,
        2.38095238,  2.85714286,  3.33333333,  3.80952381,  4.28571429,
        4.76190476,  5.23809524,  5.71428571,  6.19047619,  6.66666667,
        7.14285714,  7.61904762,  8.0952381 ,  8.57142857,  9.04761905,
        9.52380952, 10.        ])

In [ ]:
np.eye(5) # identity matrix, with 1 as diagonal

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
# random distribution function
np.random.rand(3) # random number between 0 and 3 (uniform distribution)

array([0.37187864, 0.27211267, 0.44496021])

In [ ]:
# a matrix with random numbers
np.random.rand(5,5)

array([[0.04653089, 0.09578891, 0.55117496, 0.17012963, 0.99112661],
       [0.32857752, 0.71959434, 0.11389995, 0.99116016, 0.15817407],
       [0.70086298, 0.87087865, 0.99443925, 0.63431484, 0.98863022],
       [0.93679352, 0.81627118, 0.43611001, 0.30905343, 0.82819064],
       [0.65098137, 0.82914235, 0.00687634, 0.6704835 , 0.19623332]])

In [ ]:
# a matrix with normal distribution (standard dist)
np.random.randn(4,4)

array([[-0.24966023, -0.90300729,  1.20481166,  1.15605768],
       [-0.07475981, -0.02800053, -1.68516993,  0.01540795],
       [ 1.47335837, -0.75576301,  1.4199238 ,  1.96638799],
       [ 0.46518992, -0.20015647,  0.26092211,  0.08905683]])

In [ ]:
# random numbers
np.random.randint(1,100) # one number between 0 and 100

89

In [ ]:
np.random.randint(1,100,10) # 10 numbers between 0 and 100

array([99, 70, 79, 49, 86, 94, 79, 35, 48, 89])

In [ ]:
np.random.randint(1,100,(2,3)) # 2 rows, 3 columns

array([[10, 27, 48],
       [13,  9, 85]])

In [ ]:
# reproducibility with seed
np.random.seed(42)
np.random.rand(4)
# need to run in the same cell

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

shape and reshape with numpy

In [ ]:
arr = np.arange(25) # 25 numbers from 0 to 24
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
randon_arr = np.random.randint(0,50,10)
randon_arr

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2])

In [ ]:
arr.shape # shape of the array

(25,)

In [ ]:
arr = arr.reshape(5,5) # reshape the array to a matrix 5x5
arr # cannot reshape again

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

max and min

In [ ]:
randon_arr

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2])

In [ ]:
randon_arr.max() # max value

39

In [ ]:
randon_arr.argmax() # index of the max value

7

In [ ]:
randon_arr.min() # min value

2

In [ ]:
randon_arr.argmin() # index of the min value

9

# Index Selection

In [ ]:
arr = np.arange(0,11) # create a simple array

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr[8] # index 8

8

In [ ]:
arr[1:5] # index 1 to 5
arr[:5] # index 0 to 5
arr[5:] # index 5 to the end

array([ 5,  6,  7,  8,  9, 10])

broadcasting =  ability of NumPy to treat arrays with different dimensions during arithmetic operations. Broadcasting provides a means of vectorizing array operations, therefore eliminating the need for Python loops. This is because NumPy is implemented in C Programming, which is a very efficient language.

In [ ]:
arr[:5] = 100 # replace the first 5 elements with 100

In [ ]:
arr = np.arange(0,11)

In [ ]:
slice_of_arr = arr[:5] # slice of the array

In [ ]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [ ]:
slice_of_arr[:] = 99 # replace all elements with 99
slice_of_arr

array([99, 99, 99, 99, 99])

In [ ]:
arr # the original array is also changed
# the replacing was broadcasted to the original array

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

how to avoid broadcasting???

Use `arr.copy()`

In [ ]:
arr_copy = arr.copy() # copying
arr_copy

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [ ]:
arr_copy[:] = 100

In [ ]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [ ]:
arr # the original array is not changed

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

Indexing

In [ ]:
# lets create a 2d array
arr_2d = np.array([[5,10,15], [20,25,30], [35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
arr_2d.shape # shape of the array
# 3 rows and 3 columns

(3, 3)

In [ ]:
# select the number 25
# remember that the first index in Python is 0
arr_2d[1][1] # row 1, column 1 or
arr_2d[1,1] # same

25

In [ ]:
arr_2d[2,1] # row 2, column 1

40

In [ ]:
# slicing
arr_2d[:2] # the first two rows and all columns

array([[ 5, 10, 15],
       [20, 25, 30]])

In [ ]:
arr_2d[:,:2] # all rows and the first two columns

array([[ 5, 10],
       [20, 25],
       [35, 40]])

In [ ]:
arr_2d[2:, 1:] # the last two rows and the middle two columns

array([[40, 45]])

Now, how we could filter our array?

In [ ]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr > 4 # returns a boolean array

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [ ]:
bool_arr = arr > 4 # save the boolean array

In [ ]:
arr[bool_arr] # returns the elements that are true

array([ 5,  6,  7,  8,  9, 10])

In [ ]:
# instead, we can do that using only one line
arr[arr > 4]

array([ 5,  6,  7,  8,  9, 10])

# Numpy Operations

Aritmetic operations and statistics

In [ ]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
arr - 4

array([-4, -3, -2, -1,  0,  1,  2,  3,  4,  5])

In [ ]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
# Numpy treat division by 0 different
arr / arr
# it's not an error, but a warning and a nan appears

<ipython-input-49-9ad168183d29>:2: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [ ]:
1 / arr # it's not an error, but a warning and a Inf appears

<ipython-input-50-f642029b212a>:1: RuntimeWarning: divide by zero encountered in divide
  1 / arr # it's not an error, but a warning


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

multi array function

In [ ]:
arr.sum() # sum of all elements

45

In [ ]:
arr.mean() # mean of all elements

4.5

In [ ]:
arr.max() # max value

9

In [ ]:
arr.var() # variance

8.25

In [ ]:
arr.std() # standard deviation

2.8722813232690143

In [ ]:
np.log(arr) # logarithm

<ipython-input-52-78e31d58b40f>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr) # logarithm


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [ ]:
np.sqrt(arr) # square root

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [ ]:
arr_2d = np.arange(0,25).reshape(5,5) # create a 2D array
arr_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
arr_2d.sum() # sum of all elements

300

In [ ]:
# now, I want to sum not all elements, but ACROSS the rows, so it executes the COLSUM
# it needs to use the argument axis in the function .sum()
arr_2d.sum(axis=0) # 0 means ACROSS rows = COLSUM

array([50, 55, 60, 65, 70])

In [ ]:
arr_2d.sum(axis=1) # 1 means ACROSS columns = ROWSUM

array([ 10,  35,  60,  85, 110])